version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: btc_djia_data
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  ingestion:
    build: ./ingestion
    container_name: ingestion
    restart: "no"
    volumes:
      - ./data:/app/data
      - ./ingestion/.kaggle:/root/.config/kaggle:ro
    depends_on:
      - mysql
    command: python ingest.py

  spark:
    build: ./spark
    container_name: spark
    restart: "no"
    environment:
      - SPARK_DRIVER_MEMORY=2g
    volumes:
      - ./spark:/app
      - ./data:/app/data
    depends_on:
      - ingestion
      - mysql
    command: python /app/process.py

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.9
    container_name: logstash
    restart: always
    volumes:
      - ./elk:/usr/share/logstash/pipeline
      - ./logs:/app/logs
      - ./data/processed:/usr/share/logstash/data/processed
    depends_on:
      - elasticsearch
    ports:
      - "5000:5000"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: kibana
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

volumes:
  esdata:
